### ISSUE TITLE
simulate individual transition time and states

### ISSUE THREAD

**Issue by sdaza** [hesim-dev/hesim#13]
Hello, 

Thanks for your nice package. 

I wonder if there anyway to recreate individual simulated data with states and time info. Example: 

```
id from to time status
1  1 2 3 1
1  1 3 3 0
...
```

**Comment by dincerti** [comment]
Hi and apologies for the delayed response. 

Unfortunately, the package cannot currently do this because it does not simulate right censored data. If you did not care about the `status` column, then you could fit a parametric multi-state model with `flexsurv` and then simulate it as in the [multi-state modeling vignette](https://hesim-dev.github.io/hesim/articles/mstate.html).

**Comment by dincerti** [comment]
As an additional follow-up, this can be implemented in `hesim` fairly easily with minor extensions to the existing functionality. I've done so in a 3-state case. I'm going to close this issue and open a new issue requesting this as a feature enhancement.
